# Generated by Django 3.1.2 on 2020-11-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('profissional', models.CharField(choices=[('med', 'Médico(a)'), ('enf', 'enfermeiro(a)')], max_length=3)),
                ('data', models.DateField()),
                ('turno', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde')], max_length=5)),
            ],
        ),
    ]
